### ISSUE TITLE
Error in scar executions, possibly from docker pull

### ISSUE THREAD

**Issue by csbao** [grycap/scar#206] opened 2017-12-20 00:26 UTC
Hello,

On 12/15/17, `scar run ...` has started throwing me an interesting error

```
Error: no files downloaded
Error: create container: imagerepo is invalid
Error: image or container not available
```

I noticed that when it tries to pull my base container from Docker Hub for execution, I see 9 Cloudwatch logs for 
`Error: in download: HTTP/1.1 400 Bad Request : 0` , and then 9 logs reporting that it's `Downloading layer: sha256: xxxx`. All downstream stages like creating a udocker container and container execution thus end up failing. 

Does anyone know what might be the cause of this?

**Comment by gmolto** [comment] 2017-12-20 13:15
Hi @csbao. Thank you for the issue. 

There was no change in SCAR, no change in uDocker and apparently no change in AWS Lamba, but  starting yesterday uDocker cannot pull images from Docker Hub when it is being run within AWS (see: https://github.com/indigo-dc/udocker/issues/110). 

We are still investigating this.

**Comment by alpegon** [comment] 2017-12-21 11:09
Hi @csbao the issue has been fixed and scar is up and running again !

**Comment by gmolto** [comment] 2017-12-21 17:21
Thanks @alpegon. @csbao Further details of the root cause of this problem are available in https://github.com/indigo-dc/udocker/issues/110
Closing this issue.

**Closed by gmolto** 2017-12-21 17:21 UTC
Labels: P1

**Comment by csbao** [comment] 2017-12-21 22:46
@gmolto @alpegon Thanks for the quick fix!
