### ISSUE TITLE
Getting AccessDenied while trying out few examples

### ISSUE THREAD

**Issue by neotheicebird** [grycap/scar#306] opened 2019-02-21 07:37 UTC
Scar ends up with `AccessDenied` for few examples like `ffmpeg` or `imagemagick`. I understand that its most likely a permission issue, but I don't see how. `aws cli` is configured with an admin user and the lambda role ARN added to `.scar/scar.cfg` also has `AdministratorAccess` attached to it in IAM.

Am I missing out something silly? Any help is appreciated.

Great idea btw. Thanks.

**Comment by neotheicebird** [comment] 2019-02-21 07:52
Instead of `AdministratorAccess` permissions I tried a IAM Role with the following permissions

```
AmazonS3FullAccess
AWSLambdaBasicExecutionRole
```
Still getting an Access Denied. Here is what I executed:

```
~/scar/examples/plant-classification$ python ../../scar.py init -f scar-plant-classification.yaml
Info: installing 1.1.3
Packing udocker files
Creating function package
Function 'scar-plant-classification' successfully created.
Log group '/aws/lambda/scar-plant-classification' successfully created.
There was an exception in find_bucket
Access Denied
```

**Comment by gmolto** [comment] 2019-02-21 12:43
Hi @neotheicebird and thanks for the interest in these project.
The permissions assigned to the IAM Role are used to determine the permissions of the Lambda function. Instead, the "Access Denied" error that you are obtaining is related to the permissions assigned to the IAM user whose credentials are indicated in `$HOME/.aws/credentials`. These credentials should belong to an IAM user with special permissions to access Amazon S3.

For this, check the IAM console and find out the permissions allocated to that user and check if access to S3 is enabled.

**Comment by neotheicebird** [comment] 2019-02-23 09:51
@gmolto Thanks for your response. 

I have many profiles in aws credentials, and the default profile is has an admin keypair. I assume `scar` will pick up the default profile. Also to suggest a feature, `--profile` parameter would be useful. Thanks!

**Comment by alpegon** [comment] 2019-02-23 10:00
Hi @neotheicebird, SCAR has a `--profile` option that should work.
Try the command that you are using with the extra parameter `-pf` or `--profile` and then the name of the profile that you want to use.
Cheers !

**Comment by neotheicebird** [comment] 2019-02-23 11:45
@alpegon that's awesome. Thanks!

**Comment by alpegon** [comment] 2019-03-01 12:04
Looks like the problem is solved, so I'm closing the issue.

**Closed by alpegon** 2019-03-01 12:04 UTC
