### ISSUE TITLE
Unknown parameter in input: "Tags"

### ISSUE THREAD

**Issue by gmolto** [grycap/scar#170] opened 2017-07-02 17:42 UTC
On an Ubuntu 14.04 box with an updated version of Boto (updated with `pip install -U boto` to version 2.47.0, attempting to run `scar init` yields the following error:

```sh
Traceback (most recent call last):
  File "/home/ubuntu/scar/scar.py", line 843, in <module>
    CmdParser().execute()
  File "/home/ubuntu/scar/scar.py", line 837, in execute
    args.func(args)
  File "/home/ubuntu/scar/scar.py", line 89, in init
    Tags=Config.lambda_tags)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 518, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 573, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "Tags", must be one of: FunctionName, Runtime, Role, Handler, Code, Description, Timeout, MemorySize, Publish, VpcConfig, DeadLetterConfig, Environment, KMSKeyArn
```
On an OS X 10.12.5 machine with the very same version of Boto installed, the error is not obtained.

**Comment by adokter** [comment] 2017-10-13 17:56
I have the same problem on Ubuntu 16.04 LTS. If I comment out [this line](https://github.com/grycap/scar/blob/3e0d7b680c799b905ccada3be7de39b56781f8c3/scar.py#L99) in `scar.py` script (i.e. suppress the setting of the Tags parameter in a boto3 call), the problem is solved

**Comment by adokter** [comment] 2017-10-13 18:00
I had the same problem on Ubuntu 16.04 LTE. The issue was solved by updating boto3:
```
sudo pip install -U boto3 
```

**Comment by alpegon** [comment] 2017-12-12 09:25
I'm closing this. If it happens again I will reopen the issue.

**Closed by alpegon** 2017-12-12 09:25 UTC
